version: '3.8'

services:
  app:
    container_name: gymhelper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=GymHelper;User Id=sa;Password=gympassword;
    volumes:
      - ./GymHelper:/app/GymHelper
      - ./GymHelper.Application:/app/GymHelper.Application
      - ./GymHelper.Domain:/app/GymHelper.Domain
      - ./GymHelper.Exceptions:/app/GymHelper.Exceptions
      - ./GymHelper.Infrastructure:/app/GymHelper.Infrastructure
      - ./GymHelper.Tests:/app/GymHelper.Tests
      -  nuget-cache:/root/.nuget/packages
    working_dir: /app/GymHelper
    command: ["dotnet", "watch", "run", "--urls", "http://*:5000"]
    depends_on:
      - database

  database:
    container_name: gymhelper-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gymhelper
      POSTGRES_PASSWORD: gympassword
      POSTGRES_DB: GymHelper
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  pgdata:
  pgadmin_data:
  nuget-cache:
